// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqO883nGV4Wvba29idZOrvuHNhppt4QJk',
    appId: '1:918152792596:web:5709196692d603c644b501',
    messagingSenderId: '918152792596',
    projectId: 'inventario-ibp',
    authDomain: 'inventario-ibp.firebaseapp.com',
    storageBucket: 'inventario-ibp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAprukdoOP7Y9jHH-qRQM_e8iFpTyHg5zg',
    appId: '1:918152792596:android:b7f84a0bd5add3e844b501',
    messagingSenderId: '918152792596',
    projectId: 'inventario-ibp',
    storageBucket: 'inventario-ibp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrzhTlJylZaYYFl4NSLY3E2_uPXmxjY5A',
    appId: '1:918152792596:ios:40d0b829d7f6ff8044b501',
    messagingSenderId: '918152792596',
    projectId: 'inventario-ibp',
    storageBucket: 'inventario-ibp.appspot.com',
    iosClientId: '918152792596-307q03snp536d70cd2hvofjadtsl27e8.apps.googleusercontent.com',
    iosBundleId: 'com.example.invetarioFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrzhTlJylZaYYFl4NSLY3E2_uPXmxjY5A',
    appId: '1:918152792596:ios:40d0b829d7f6ff8044b501',
    messagingSenderId: '918152792596',
    projectId: 'inventario-ibp',
    storageBucket: 'inventario-ibp.appspot.com',
    iosClientId: '918152792596-307q03snp536d70cd2hvofjadtsl27e8.apps.googleusercontent.com',
    iosBundleId: 'com.example.invetarioFlutter',
  );
}
